language: android
script: ./CityFeels/gradlew.bat
notifications:
  slack: ldso2015g1:jwK6sZS7tJ0gfXAASdA5Ikaj
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    # - tools

    # The BuildTools version used by your project
    - build-tools-23.0.2

    # The SDK version used to compile your project
    - android-23

    # Additional components
    - extra-google-google_play_services

   
